### ISSUE TITLE
Support Magento Open Source

### ISSUE THREAD

**Issue by mattijv** [paytrail/paytrail-for-adobe-commerce-graphql#4]
**Is your feature request related to a problem? Please describe.**

The class `Magento\Support\Model\Report\Group\Modules\Modules` does not exist in the Magento Open Source (there's no `Magento_Support` module there), so the package is not usable there.

**Describe the solution you'd like**

Changing the code to use `Magento\Framework\Module\Manager` is a trivial fix to the issue (as is done in [this PR](https://github.com/paytrail/paytrail-for-adobe-commerce-graphql/pull/3)).

**Describe alternatives you've considered**

Alternative is to fork the package and do the change above ourselves, but that feels suboptimal.

**Comment by konrad-konieczny** [comment]
Hi @mattijv,
thank you for your report, we will check the issue and let you know when it is done.

**Comment by konrad-konieczny** [comment]
#3  already merged, I'm closing now the issue.
